spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgres:///demo01_security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  redis:
    port: 6379
    password: 1j23456
    host: localhost
  session:
    store-type: redis
    timeout: 300s
    redis:
      cleanup-cron: 0 */30 * * * ?
server:
  port: 8091
